# P.Itarun xOps-CPE 
# kasmweb ubuntu desktop 20.04
# user: kasm_user
# set env var before deploy
# PASSWORD=changeme
#
version: '3.3'
services:
  kasm_web:
    image: ipvsix/ubuntu-desktop:jun22
    shm_size: '512mb'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VNC_PW: '${PASSWORD}'
    ports:
      - 6901
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.2'
          memory: 256M
        limits:
          cpus: '4.0'
          memory: 4G


